name: Test Suite

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
        php:
          - 8.1
        laravel:
          - 10.*
        stability:
          - prefer-lowest
          - prefer-stable
        include:
          - laravel: 10.*
            testbench: 8.*

    name: PHP-${{ matrix.php }} -- Laravel-${{ matrix.laravel }} -- ${{ matrix.stability }} -- ${{ matrix.os }}

    steps:

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Install Dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: Run Static Analysis
        run: composer run stan

      - name: Run Tests
        run: composer run test
